apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}-service
  namespace: {{ .Values.application.namespace }}
  labels:
    app: {{ .Values.postgres.name }}
spec:
  selector:
    app: {{ .Values.postgres.name }}
  ports:
    - port: {{ .Values.postgres.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}-service
  namespace: {{ .Values.application.namespace }}
  labels:
    app: {{ .Values.backend.name }}
spec:
  selector:
    app: {{ .Values.backend.name }}
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30401